debug: true
spring:
  application:
    name: eureka-consumer-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试
eureka-client:
  ribbon:
    ConnectTimeout: 250 #请求连接的超时时间
    ReadTimeout: 10000 #请求处理的超时时间
    MaxAutoRetries: 2 #对当前实例的重试次数
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    OkToRetryOnAllOperations: true #对所有操作请求都进行重试
server:
  port: 8130
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/    #defaultZone: http://manager1:8100/eureka/,http://manager2:8100/eureka/,http://manager3:8100/eureka/
