debug: true
spring:
  application:
    name: eureka-consumer-hystrix-with-feign
  rabbitmq:
    host: manager1
    port: 8001
    username: admin
    password: admin123
server:
  port: 8160
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/    #defaultZone: http://manager1:8100/eureka/,http://manager2:8100/eureka/,http://manager3:8100/eureka/
feign:
  hystrix:
    enabled: true