debug: true
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false  #表示当前程序不使用sleuth
  #rabbitmq: #使用RabbitMQ消息队列进行数据收集
  #  host: manager1
  #  port: 8001
  #  username: admin
  #  password: admin123
#zipkin:
#  storage:
#    type: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      max-requests: 30
#      index: zipkin
#      index-shards: 3
#      index-replicas: 1
#      hosts: node1:9200
server:
  port: 8270
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/    #defaultZone: http://manager1:8100/eureka/,http://manager2:8100/eureka/,http://manager3:8100/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90  #失效时间（超过一定时间还没有检查心跳通过，从服务中心剔除），默认90秒，生产环境建议10秒
    lease-renewal-interval-in-seconds: 30 #心跳时间（类似于健康检查时间间隔），默认30秒，生产环境建议3秒