spring:
  application:
    name: eureka-consumer
  rabbitmq:
    host: manager1
    port: 8001
    username: admin
    password: admin123
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8120
swagger:
  base-package: com.xishuai.demo.eurekaconsumer
  title: Eureka Consumer 服务
  description: 测试服务
  version: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/    #defaultZone: http://manager1:8100/eureka/,http://manager2:8100/eureka/,http://manager3:8100/eureka/